font_family      JetBrainsMono Nerd Font
font_size        15.0

background  #ebdbb3
foreground #000000
background_opacity  1.0

scrollback_lines 5000
window_padding_width 10

map cmd+alt+t new_window
