# Autostart
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
exec-once=fcitx5-remote -r
exec-once=fcitx5 -d --replace
exec-once=fcitx5-remote -r
# exec-once=$HOME/.local/bin/ABDownloadManager

# Sourcing external config files
source= keybinds.conf
source= startup.conf
source= Laptops.conf # For laptop related
source= decorations.conf # Decorations and animations config file
source= settings.conf # Main Hyprland Settings.
source= defaults.conf # defaults apps
source= wrules.conf # window rules

# system environment variables
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = CLUTTER_BACKEND,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME,qt6ct
env = GDK_SCALE,1
env = QT_SCALE_FACTOR,1
env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_SIZE,24
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,auto # for electron apps


# LAYER RULES
# layerrule = blur, rofi
# layerrule = ignorezero, rofi
# layerrule = blur, notifications
# layerrule = ignorezero, notifications
# and ends here
