-- Autostart
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.env("GBM_BACKEND", "nvidia-drm")
-- Sourcing external config files
-- Source: keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("keybinds")
-- Source: startup.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("startup")
-- Source: Laptops.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("Laptops")
-- Source: decorations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("decorations")
-- Source: settings.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("settings")
-- Source: defaults.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("defaults")
-- Source: wrules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("wrules")

-- system environment variables
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("GDK_SCALE", "1")
hl.env("QT_SCALE_FACTOR", "1")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("WLR_DRM_DEVICES", "/dev/dri/card0:/dev/dri/card1")
-- Force Mesa driver backend
hl.env("LIBGL_ALWAYS_SOFTWARE", "0")
hl.env("WLR_NO_HARDWARE_CURSORS", "1")

-- For Dual GPU (Intel + NVIDIA)
hl.env("AQ_DRM_DEVICES", "/dev/dri/card1:/dev/dri/card0")

-- Disable forcing linear modifiers on Multi-GPU buffers (may help Nvidia issues)
hl.env("AQ_FORCE_LINEAR_BLIT", "0")

-- Disable explicit syncing on multi-GPU buffers
hl.env("AQ_MGPU_NO_EXPLICIT", "1")
-- LAYER RULES
-- layerrule = blur, rofi
-- layerrule = ignorezero, rofi
-- layerrule = blur, notifications
-- layerrule = ignorezero, notifications
-- and ends here
hl.config({
    render = {
        direct_scanout = false,
    },
})

hl.on("hyprland.start", function()
    hl.exec_cmd("fcitx5-remote -r")
    hl.exec_cmd("fcitx5 -d --replace")
    hl.exec_cmd("fcitx5-remote -r")
end)

