-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local Touchpad_Device = "asue1209:00-04f3:319f-touchpad"
local TOUCHPAD_ENABLED = true
hl.device({
    name = Touchpad_Device,
    enabled = TOUCHPAD_ENABLED,
})

