-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
local home = os.getenv("HOME")
local scriptsDir = home .. "/.config/hypr/scripts"
local UserScripts = home .. "/.config/hypr/usercfg"

local wallDIR = home .. "/.config/hypr/wallpapers"
local lock = scriptsDir .. "/LockScreen.sh"
local SwwwRandom = UserScripts .. "/WallpaperAutoChange.sh"
local livewallpaper = "\"\""
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd(scriptsDir .. "/Polkit.sh")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("spoofdpi")
    hl.exec_cmd("/usr/libexec/fcitx5-wayland-launcher")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd(UserScripts .. "/RainbowBorders.sh")
    hl.exec_cmd("swaync")
    hl.exec_cmd("waybar")
    hl.exec_cmd("nwg-panel")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("awww-daemon")
end)

