-- Windows rules starts here
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "class:^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr|[Ff]irefox-bin)$",
    },
    tag = "+browser",
})

hl.window_rule({
    match = {
        class = "class:^(chrome-.+-Default)$",
    },
    tag = "+browser",
})

hl.window_rule({
    match = {
        class = "class:^([Cc]hromium)$",
    },
    tag = "+browser",
})

hl.window_rule({
    match = {
        class = "class:^(zen-alpha|zen)$",
    },
    tag = "+browser",
})

-- notif tags
hl.window_rule({
    match = {
        class = "class:^(swaync-control-center|swaync-notification-window|swaync-client|class)$",
    },
    tag = "+notif",
})

-- KooL settings tag
hl.window_rule({
    match = {
        class = "title:^(KooL Quick Cheat Sheet)$",
    },
    tag = "+KooL_Cheat",
})

-- terminal tags
hl.window_rule({
    match = {
        class = "class:^(Alacritty|kitty|kitty-dropterm)$",
    },
    tag = "+terminal",
})

-- project tags
hl.window_rule({
    match = {
        class = "class:^(codium|codium-url-handler|VSCodium)$",
    },
    tag = "+projects",
})

hl.window_rule({
    match = {
        class = "class:^(VSCode|code-url-handler)$",
    },
    tag = "+projects",
})

-- screenshare tags
hl.window_rule({
    match = {
        class = "class:^(com.obsproject.Studio)$",
    },
    tag = "+screenshare",
})

-- IM tags
hl.window_rule({
    match = {
        class = "class:^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$",
    },
    tag = "+im",
})

hl.window_rule({
    match = {
        class = "class:^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$",
    },
    tag = "+im",
})

-- game tags
hl.window_rule({
    match = {
        class = "class:^(gamescope)$",
    },
    tag = "+games",
})

hl.window_rule({
    match = {
        class = "class:^(steam_app_\\d+)$",
    },
    tag = "+games",
})

-- gamestore tags
hl.window_rule({
    match = {
        class = "class:^([Ss]team)$",
    },
    tag = "+gamestore",
})

hl.window_rule({
    match = {
        class = "title:^([Ll]utris)$",
    },
    tag = "+gamestore",
})

hl.window_rule({
    match = {
        class = "class:^(com.heroicgameslauncher.hgl)$",
    },
    tag = "+gamestore",
})

-- file-manager tags
hl.window_rule({
    match = {
        class = "class:^([Tt]hunar|org.gnome.Nautilus|[Pp]cmanfm-qt)$",
    },
    tag = "+file-manager",
})

-- multimedia tags
hl.window_rule({
    match = {
        class = "class:^([Aa]udacious)$",
    },
    tag = "+multimedia",
})

-- multimedia-video tags
hl.window_rule({
    match = {
        class = "class:^([Mm]pv|vlc)$",
    },
    tag = "+multimedia_video",
})

-- settings tags
hl.window_rule({
    match = {
        class = "class:^(gnome-disks|wihotspot(-gui)?)$",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "title:(Kvantum Manager)",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:^(file-roller|org.gnome.FileRoller)$",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:^(nm-applet|nm-connection-editor|blueman-manager)$",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:^(qt5ct|qt6ct|[Yy]ad)$",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:(xdg-desktop-portal-gtk)",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:^(org.kde.polkit-kde-authentication-agent-1)$",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:^([Rr]ofi)$",
    },
    tag = "+settings",
})

-- viewer tags
hl.window_rule({
    match = {
        class = "class:^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter)$",
    },
    tag = "+viewer",
})

hl.window_rule({
    match = {
        class = "class:^(evince)$",
    },
    tag = "+viewer",
})

hl.window_rule({
    match = {
        class = "class:^(eog|org.gnome.Loupe)$",
    },
    tag = "+viewer",
})

hl.window_rule({
    match = {
        class = "class:^(xwkh)$",
    },
    tag = "+xwkh",
})

-- Some special override rules
hl.window_rule({
    match = {
        class = "tag:multimedia_video*",
    },
    no_blur = true,
    opacity = 1.0,
})

-- POSITION
-- windowrule = center,floating:1 # warning, it cause even the menu to float and center.
hl.window_rule({
    match = {
        class = "tag:KooL_Cheat*",
    },
    center = true,
})

hl.window_rule({
    center = true,
    -- TODO: manual review — unmapped window rule action: "class:([Tt]hunar)"
    -- TODO: manual review — unmapped window rule action: "title:negative:(.*[Tt]hunar.*)"
})

hl.window_rule({
    match = {
        class = "tag:KooL-Settings*",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "title:^(Keybindings)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "class:^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "title:^(Picture-in-Picture)$",
    },
    move = "72% 7%",
})

hl.window_rule({
    match = {
        class = "fullscreen:1",
    },
    -- TODO: manual review — unmapped window rule action: "idleinhibit fullscreen"
})

-- FLOAT
hl.window_rule({
    match = {
        class = "tag:KooL_Cheat*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "tag:wallpaper*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "tag:settings*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "tag:viewer*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "tag:KooL-Settings*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "class:([Zz]oom|onedriver|onedriver-launcher)$",
    },
    float = true,
})

hl.window_rule({
    float = true,
    -- TODO: manual review — unmapped window rule action: "class:(org.gnome.Calculator)"
    -- TODO: manual review — unmapped window rule action: "title:(Calculator)"
})

hl.window_rule({
    match = {
        class = "class:^(mpv|com.github.rafostar.Clapper)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "class:^([Qq]alculate-gtk)$",
    },
    float = true,
})

--windowrule = float, class:^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$
hl.window_rule({
    match = {
        class = "class:^([Ff]erdium)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "title:^(Picture-in-Picture)$",
    },
    float = true,
})

--windowrule = float, title:^(Firefox)$

-- windowrule - ######### float popups and dialogue #######
hl.window_rule({
    match = {
        class = "title:^(Authentication Required)$",
    },
    float = true,
    center = true,
})

hl.window_rule({
    float = true,
    -- TODO: manual review — unmapped window rule action: "class:(codium|codium-url-handler|VSCodium)"
    -- TODO: manual review — unmapped window rule action: "title:negative:(.*codium.*|.*VSCodium.*)"
    float = true,
    -- TODO: manual review — unmapped window rule action: "class:^(com.heroicgameslauncher.hgl)$"
    -- TODO: manual review — unmapped window rule action: "title:negative:(Heroic Games Launcher)"
    float = true,
    -- TODO: manual review — unmapped window rule action: "class:^([Ss]team)$"
    -- TODO: manual review — unmapped window rule action: "title:negative:^([Ss]team)$"
    float = true,
    -- TODO: manual review — unmapped window rule action: "class:([Tt]hunar)"
    -- TODO: manual review — unmapped window rule action: "title:negative:(.*[Tt]hunar.*)"
})

hl.window_rule({
    match = {
        class = "title:^(Add Folder to Workspace)$",
    },
    float = true,
    size = "70% 60%",
    center = true,
})

hl.window_rule({
    match = {
        class = "title:^(Save As)$",
    },
    float = true,
    size = "70% 60%",
    center = true,
})

hl.window_rule({
    match = {
        class = "initialTitle:(Open Files)",
    },
    float = true,
    size = "70% 60%",
})

hl.window_rule({
    match = {
        class = "title:^(SDDM Background)$",
    },
    float = true,
    center = true,
    size = "16% 12%",
})

-- END of float popups and dialogue #######

-- OPACITY
hl.window_rule({
    match = {
        class = "tag:browser*",
    },
    opacity = "0.9 0.7",
})

hl.window_rule({
    match = {
        class = "tag:projects*",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    match = {
        class = "tag:im*",
    },
    opacity = "0.94 0.86",
})

hl.window_rule({
    match = {
        class = "tag:multimedia*",
    },
    opacity = "0.94 0.86",
})

hl.window_rule({
    match = {
        class = "tag:file-manager*",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    match = {
        class = "tag:terminal*",
    },
    opacity = "0.8 0.7",
})

hl.window_rule({
    match = {
        class = "tag:settings*",
    },
    opacity = "0.8 0.7",
})

hl.window_rule({
    match = {
        class = "tag:viewer*",
    },
    opacity = "0.82 0.75",
})

hl.window_rule({
    match = {
        class = "tag:wallpaper*",
    },
    opacity = "0.9 0.7",
})

hl.window_rule({
    match = {
        class = "class:^(gedit|org.gnome.TextEditor|mousepad)$",
    },
    opacity = "0.8 0.7",
})

hl.window_rule({
    match = {
        class = "tag:xwkh*",
    },
    opacity = "0.5 0.5",
})

hl.window_rule({
    match = {
        class = "class:^(deluge)$",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    match = {
        class = "class:^(seahorse)$",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    match = {
        class = "title:^(Picture-in-Picture)$",
    },
    opacity = "0.95 0.75",
})

-- SIZE
hl.window_rule({
    match = {
        class = "tag:KooL_Cheat*",
    },
    size = "65% 90%",
})

hl.window_rule({
    match = {
        class = "tag:wallpaper*",
    },
    size = "70% 70%",
})

hl.window_rule({
    match = {
        class = "tag:settings*",
    },
    size = "70% 70%",
})

hl.window_rule({
    match = {
        class = "class:^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$",
    },
    size = "60% 70%",
})

hl.window_rule({
    match = {
        class = "class:^([Ff]erdium)$",
    },
    size = "60% 70%",
})

-- PINNING
hl.window_rule({
    match = {
        class = "title:^(Picture-in-Picture)$",
    },
    pin = true,
})

--windowrule = pin,title:^(Firefox)$ 

-- windowrule - extras
hl.window_rule({
    match = {
        class = "title:^(Picture-in-Picture)$",
    },
    -- TODO: manual review — unmapped window rule action: "keepaspectratio"
})

-- BLUR & FULLSCREEN
hl.window_rule({
    match = {
        class = "tag:games*",
    },
    no_blur = true,
    fullscreen = true,
})

