# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #201B2D
background         #FFFFF7
cursor             #5C575E

active_tab_foreground     #FFFFF7
active_tab_background     #201B2D
inactive_tab_foreground   #201B2D
inactive_tab_background   #FFFFF7

active_border_color   #201B2D
inactive_border_color #FFFFF7
bell_border_color     #91635D

color0      #FFFFF7
color1		#91635D
color2		#726F6B
color3		#5B5965
color4		#8C404C
color5		#504A5A
color6		#352C4C
color7		#201B2D
color8		#97987B
color9		#C2847C
color10		#98948F
color11		#797787
color12		#BB5565
color13		#6B6378
color14		#463B65
color15		#0B090F
