-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
-- /* wallust template - colors-hyprland */ 

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local background = "rgb(FCE7ED)"
local foreground = "rgb(0C060D)"
local color0 = "rgb(FFFAFF)"
local color1 = "rgb(914B64)"
local color2 = "rgb(80443B)"
local color3 = "rgb(693C77)"
local color4 = "rgb(462536)"
local color5 = "rgb(181F67)"
local color6 = "rgb(140B15)"
local color7 = "rgb(0C060D)"
local color8 = "rgb(99586F)"
local color9 = "rgb(C16486)"
local color10 = "rgb(AB5B4F)"
local color11 = "rgb(8C509F)"
local color12 = "rgb(5D3148)"
local color13 = "rgb(202989)"
local color14 = "rgb(1B0E1C)"
local color15 = "rgb(040204)"
